# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ateixeira/dev/RTPlot

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ateixeira/dev/RTPlot

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ateixeira/dev/RTPlot/CMakeFiles /home/ateixeira/dev/RTPlot//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ateixeira/dev/RTPlot/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RTPlot

# Build rule for target.
RTPlot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RTPlot
.PHONY : RTPlot

# fast build rule for target.
RTPlot/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/build
.PHONY : RTPlot/fast

src/core/DeviceManager.o: src/core/DeviceManager.cpp.o
.PHONY : src/core/DeviceManager.o

# target to build an object file
src/core/DeviceManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/core/DeviceManager.cpp.o
.PHONY : src/core/DeviceManager.cpp.o

src/core/DeviceManager.i: src/core/DeviceManager.cpp.i
.PHONY : src/core/DeviceManager.i

# target to preprocess a source file
src/core/DeviceManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/core/DeviceManager.cpp.i
.PHONY : src/core/DeviceManager.cpp.i

src/core/DeviceManager.s: src/core/DeviceManager.cpp.s
.PHONY : src/core/DeviceManager.s

# target to generate assembly for a file
src/core/DeviceManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/core/DeviceManager.cpp.s
.PHONY : src/core/DeviceManager.cpp.s

src/core/RTPlotCore.o: src/core/RTPlotCore.cpp.o
.PHONY : src/core/RTPlotCore.o

# target to build an object file
src/core/RTPlotCore.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/core/RTPlotCore.cpp.o
.PHONY : src/core/RTPlotCore.cpp.o

src/core/RTPlotCore.i: src/core/RTPlotCore.cpp.i
.PHONY : src/core/RTPlotCore.i

# target to preprocess a source file
src/core/RTPlotCore.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/core/RTPlotCore.cpp.i
.PHONY : src/core/RTPlotCore.cpp.i

src/core/RTPlotCore.s: src/core/RTPlotCore.cpp.s
.PHONY : src/core/RTPlotCore.s

# target to generate assembly for a file
src/core/RTPlotCore.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/core/RTPlotCore.cpp.s
.PHONY : src/core/RTPlotCore.cpp.s

src/core/RTPlotFunctions.o: src/core/RTPlotFunctions.cpp.o
.PHONY : src/core/RTPlotFunctions.o

# target to build an object file
src/core/RTPlotFunctions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/core/RTPlotFunctions.cpp.o
.PHONY : src/core/RTPlotFunctions.cpp.o

src/core/RTPlotFunctions.i: src/core/RTPlotFunctions.cpp.i
.PHONY : src/core/RTPlotFunctions.i

# target to preprocess a source file
src/core/RTPlotFunctions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/core/RTPlotFunctions.cpp.i
.PHONY : src/core/RTPlotFunctions.cpp.i

src/core/RTPlotFunctions.s: src/core/RTPlotFunctions.cpp.s
.PHONY : src/core/RTPlotFunctions.s

# target to generate assembly for a file
src/core/RTPlotFunctions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/core/RTPlotFunctions.cpp.s
.PHONY : src/core/RTPlotFunctions.cpp.s

src/files/FileManager.o: src/files/FileManager.cpp.o
.PHONY : src/files/FileManager.o

# target to build an object file
src/files/FileManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/files/FileManager.cpp.o
.PHONY : src/files/FileManager.cpp.o

src/files/FileManager.i: src/files/FileManager.cpp.i
.PHONY : src/files/FileManager.i

# target to preprocess a source file
src/files/FileManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/files/FileManager.cpp.i
.PHONY : src/files/FileManager.cpp.i

src/files/FileManager.s: src/files/FileManager.cpp.s
.PHONY : src/files/FileManager.s

# target to generate assembly for a file
src/files/FileManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/files/FileManager.cpp.s
.PHONY : src/files/FileManager.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/plotting/ColorPalette.o: src/plotting/ColorPalette.cpp.o
.PHONY : src/plotting/ColorPalette.o

# target to build an object file
src/plotting/ColorPalette.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/plotting/ColorPalette.cpp.o
.PHONY : src/plotting/ColorPalette.cpp.o

src/plotting/ColorPalette.i: src/plotting/ColorPalette.cpp.i
.PHONY : src/plotting/ColorPalette.i

# target to preprocess a source file
src/plotting/ColorPalette.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/plotting/ColorPalette.cpp.i
.PHONY : src/plotting/ColorPalette.cpp.i

src/plotting/ColorPalette.s: src/plotting/ColorPalette.cpp.s
.PHONY : src/plotting/ColorPalette.s

# target to generate assembly for a file
src/plotting/ColorPalette.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/plotting/ColorPalette.cpp.s
.PHONY : src/plotting/ColorPalette.cpp.s

src/plotting/Logger.o: src/plotting/Logger.cpp.o
.PHONY : src/plotting/Logger.o

# target to build an object file
src/plotting/Logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/plotting/Logger.cpp.o
.PHONY : src/plotting/Logger.cpp.o

src/plotting/Logger.i: src/plotting/Logger.cpp.i
.PHONY : src/plotting/Logger.i

# target to preprocess a source file
src/plotting/Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/plotting/Logger.cpp.i
.PHONY : src/plotting/Logger.cpp.i

src/plotting/Logger.s: src/plotting/Logger.cpp.s
.PHONY : src/plotting/Logger.s

# target to generate assembly for a file
src/plotting/Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/plotting/Logger.cpp.s
.PHONY : src/plotting/Logger.cpp.s

src/plotting/PlotData.o: src/plotting/PlotData.cpp.o
.PHONY : src/plotting/PlotData.o

# target to build an object file
src/plotting/PlotData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/plotting/PlotData.cpp.o
.PHONY : src/plotting/PlotData.cpp.o

src/plotting/PlotData.i: src/plotting/PlotData.cpp.i
.PHONY : src/plotting/PlotData.i

# target to preprocess a source file
src/plotting/PlotData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/plotting/PlotData.cpp.i
.PHONY : src/plotting/PlotData.cpp.i

src/plotting/PlotData.s: src/plotting/PlotData.cpp.s
.PHONY : src/plotting/PlotData.s

# target to generate assembly for a file
src/plotting/PlotData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/plotting/PlotData.cpp.s
.PHONY : src/plotting/PlotData.cpp.s

src/plotting/Plotter.o: src/plotting/Plotter.cpp.o
.PHONY : src/plotting/Plotter.o

# target to build an object file
src/plotting/Plotter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/plotting/Plotter.cpp.o
.PHONY : src/plotting/Plotter.cpp.o

src/plotting/Plotter.i: src/plotting/Plotter.cpp.i
.PHONY : src/plotting/Plotter.i

# target to preprocess a source file
src/plotting/Plotter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/plotting/Plotter.cpp.i
.PHONY : src/plotting/Plotter.cpp.i

src/plotting/Plotter.s: src/plotting/Plotter.cpp.s
.PHONY : src/plotting/Plotter.s

# target to generate assembly for a file
src/plotting/Plotter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/plotting/Plotter.cpp.s
.PHONY : src/plotting/Plotter.cpp.s

src/plotting/RealTimePlot.o: src/plotting/RealTimePlot.cpp.o
.PHONY : src/plotting/RealTimePlot.o

# target to build an object file
src/plotting/RealTimePlot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/plotting/RealTimePlot.cpp.o
.PHONY : src/plotting/RealTimePlot.cpp.o

src/plotting/RealTimePlot.i: src/plotting/RealTimePlot.cpp.i
.PHONY : src/plotting/RealTimePlot.i

# target to preprocess a source file
src/plotting/RealTimePlot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/plotting/RealTimePlot.cpp.i
.PHONY : src/plotting/RealTimePlot.cpp.i

src/plotting/RealTimePlot.s: src/plotting/RealTimePlot.cpp.s
.PHONY : src/plotting/RealTimePlot.s

# target to generate assembly for a file
src/plotting/RealTimePlot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/plotting/RealTimePlot.cpp.s
.PHONY : src/plotting/RealTimePlot.cpp.s

src/plotting/RollingBuffer.o: src/plotting/RollingBuffer.cpp.o
.PHONY : src/plotting/RollingBuffer.o

# target to build an object file
src/plotting/RollingBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/plotting/RollingBuffer.cpp.o
.PHONY : src/plotting/RollingBuffer.cpp.o

src/plotting/RollingBuffer.i: src/plotting/RollingBuffer.cpp.i
.PHONY : src/plotting/RollingBuffer.i

# target to preprocess a source file
src/plotting/RollingBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/plotting/RollingBuffer.cpp.i
.PHONY : src/plotting/RollingBuffer.cpp.i

src/plotting/RollingBuffer.s: src/plotting/RollingBuffer.cpp.s
.PHONY : src/plotting/RollingBuffer.s

# target to generate assembly for a file
src/plotting/RollingBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/plotting/RollingBuffer.cpp.s
.PHONY : src/plotting/RollingBuffer.cpp.s

src/serial/SerialDevice.o: src/serial/SerialDevice.cpp.o
.PHONY : src/serial/SerialDevice.o

# target to build an object file
src/serial/SerialDevice.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/serial/SerialDevice.cpp.o
.PHONY : src/serial/SerialDevice.cpp.o

src/serial/SerialDevice.i: src/serial/SerialDevice.cpp.i
.PHONY : src/serial/SerialDevice.i

# target to preprocess a source file
src/serial/SerialDevice.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/serial/SerialDevice.cpp.i
.PHONY : src/serial/SerialDevice.cpp.i

src/serial/SerialDevice.s: src/serial/SerialDevice.cpp.s
.PHONY : src/serial/SerialDevice.s

# target to generate assembly for a file
src/serial/SerialDevice.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/serial/SerialDevice.cpp.s
.PHONY : src/serial/SerialDevice.cpp.s

src/serial/SerialPlotter.o: src/serial/SerialPlotter.cpp.o
.PHONY : src/serial/SerialPlotter.o

# target to build an object file
src/serial/SerialPlotter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/serial/SerialPlotter.cpp.o
.PHONY : src/serial/SerialPlotter.cpp.o

src/serial/SerialPlotter.i: src/serial/SerialPlotter.cpp.i
.PHONY : src/serial/SerialPlotter.i

# target to preprocess a source file
src/serial/SerialPlotter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/serial/SerialPlotter.cpp.i
.PHONY : src/serial/SerialPlotter.cpp.i

src/serial/SerialPlotter.s: src/serial/SerialPlotter.cpp.s
.PHONY : src/serial/SerialPlotter.s

# target to generate assembly for a file
src/serial/SerialPlotter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/serial/SerialPlotter.cpp.s
.PHONY : src/serial/SerialPlotter.cpp.s

src/serial/SerialPort.o: src/serial/SerialPort.cpp.o
.PHONY : src/serial/SerialPort.o

# target to build an object file
src/serial/SerialPort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/serial/SerialPort.cpp.o
.PHONY : src/serial/SerialPort.cpp.o

src/serial/SerialPort.i: src/serial/SerialPort.cpp.i
.PHONY : src/serial/SerialPort.i

# target to preprocess a source file
src/serial/SerialPort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/serial/SerialPort.cpp.i
.PHONY : src/serial/SerialPort.cpp.i

src/serial/SerialPort.s: src/serial/SerialPort.cpp.s
.PHONY : src/serial/SerialPort.s

# target to generate assembly for a file
src/serial/SerialPort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/serial/SerialPort.cpp.s
.PHONY : src/serial/SerialPort.cpp.s

src/vendor/imgui/imgui.o: src/vendor/imgui/imgui.cpp.o
.PHONY : src/vendor/imgui/imgui.o

# target to build an object file
src/vendor/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/vendor/imgui/imgui.cpp.o
.PHONY : src/vendor/imgui/imgui.cpp.o

src/vendor/imgui/imgui.i: src/vendor/imgui/imgui.cpp.i
.PHONY : src/vendor/imgui/imgui.i

# target to preprocess a source file
src/vendor/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/vendor/imgui/imgui.cpp.i
.PHONY : src/vendor/imgui/imgui.cpp.i

src/vendor/imgui/imgui.s: src/vendor/imgui/imgui.cpp.s
.PHONY : src/vendor/imgui/imgui.s

# target to generate assembly for a file
src/vendor/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/vendor/imgui/imgui.cpp.s
.PHONY : src/vendor/imgui/imgui.cpp.s

src/vendor/imgui/imgui_demo.o: src/vendor/imgui/imgui_demo.cpp.o
.PHONY : src/vendor/imgui/imgui_demo.o

# target to build an object file
src/vendor/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/vendor/imgui/imgui_demo.cpp.o
.PHONY : src/vendor/imgui/imgui_demo.cpp.o

src/vendor/imgui/imgui_demo.i: src/vendor/imgui/imgui_demo.cpp.i
.PHONY : src/vendor/imgui/imgui_demo.i

# target to preprocess a source file
src/vendor/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/vendor/imgui/imgui_demo.cpp.i
.PHONY : src/vendor/imgui/imgui_demo.cpp.i

src/vendor/imgui/imgui_demo.s: src/vendor/imgui/imgui_demo.cpp.s
.PHONY : src/vendor/imgui/imgui_demo.s

# target to generate assembly for a file
src/vendor/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/vendor/imgui/imgui_demo.cpp.s
.PHONY : src/vendor/imgui/imgui_demo.cpp.s

src/vendor/imgui/imgui_draw.o: src/vendor/imgui/imgui_draw.cpp.o
.PHONY : src/vendor/imgui/imgui_draw.o

# target to build an object file
src/vendor/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/vendor/imgui/imgui_draw.cpp.o
.PHONY : src/vendor/imgui/imgui_draw.cpp.o

src/vendor/imgui/imgui_draw.i: src/vendor/imgui/imgui_draw.cpp.i
.PHONY : src/vendor/imgui/imgui_draw.i

# target to preprocess a source file
src/vendor/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/vendor/imgui/imgui_draw.cpp.i
.PHONY : src/vendor/imgui/imgui_draw.cpp.i

src/vendor/imgui/imgui_draw.s: src/vendor/imgui/imgui_draw.cpp.s
.PHONY : src/vendor/imgui/imgui_draw.s

# target to generate assembly for a file
src/vendor/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/vendor/imgui/imgui_draw.cpp.s
.PHONY : src/vendor/imgui/imgui_draw.cpp.s

src/vendor/imgui/imgui_impl_glfw.o: src/vendor/imgui/imgui_impl_glfw.cpp.o
.PHONY : src/vendor/imgui/imgui_impl_glfw.o

# target to build an object file
src/vendor/imgui/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/vendor/imgui/imgui_impl_glfw.cpp.o
.PHONY : src/vendor/imgui/imgui_impl_glfw.cpp.o

src/vendor/imgui/imgui_impl_glfw.i: src/vendor/imgui/imgui_impl_glfw.cpp.i
.PHONY : src/vendor/imgui/imgui_impl_glfw.i

# target to preprocess a source file
src/vendor/imgui/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/vendor/imgui/imgui_impl_glfw.cpp.i
.PHONY : src/vendor/imgui/imgui_impl_glfw.cpp.i

src/vendor/imgui/imgui_impl_glfw.s: src/vendor/imgui/imgui_impl_glfw.cpp.s
.PHONY : src/vendor/imgui/imgui_impl_glfw.s

# target to generate assembly for a file
src/vendor/imgui/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/vendor/imgui/imgui_impl_glfw.cpp.s
.PHONY : src/vendor/imgui/imgui_impl_glfw.cpp.s

src/vendor/imgui/imgui_impl_opengl3.o: src/vendor/imgui/imgui_impl_opengl3.cpp.o
.PHONY : src/vendor/imgui/imgui_impl_opengl3.o

# target to build an object file
src/vendor/imgui/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/vendor/imgui/imgui_impl_opengl3.cpp.o
.PHONY : src/vendor/imgui/imgui_impl_opengl3.cpp.o

src/vendor/imgui/imgui_impl_opengl3.i: src/vendor/imgui/imgui_impl_opengl3.cpp.i
.PHONY : src/vendor/imgui/imgui_impl_opengl3.i

# target to preprocess a source file
src/vendor/imgui/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/vendor/imgui/imgui_impl_opengl3.cpp.i
.PHONY : src/vendor/imgui/imgui_impl_opengl3.cpp.i

src/vendor/imgui/imgui_impl_opengl3.s: src/vendor/imgui/imgui_impl_opengl3.cpp.s
.PHONY : src/vendor/imgui/imgui_impl_opengl3.s

# target to generate assembly for a file
src/vendor/imgui/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/vendor/imgui/imgui_impl_opengl3.cpp.s
.PHONY : src/vendor/imgui/imgui_impl_opengl3.cpp.s

src/vendor/imgui/imgui_tables.o: src/vendor/imgui/imgui_tables.cpp.o
.PHONY : src/vendor/imgui/imgui_tables.o

# target to build an object file
src/vendor/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/vendor/imgui/imgui_tables.cpp.o
.PHONY : src/vendor/imgui/imgui_tables.cpp.o

src/vendor/imgui/imgui_tables.i: src/vendor/imgui/imgui_tables.cpp.i
.PHONY : src/vendor/imgui/imgui_tables.i

# target to preprocess a source file
src/vendor/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/vendor/imgui/imgui_tables.cpp.i
.PHONY : src/vendor/imgui/imgui_tables.cpp.i

src/vendor/imgui/imgui_tables.s: src/vendor/imgui/imgui_tables.cpp.s
.PHONY : src/vendor/imgui/imgui_tables.s

# target to generate assembly for a file
src/vendor/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/vendor/imgui/imgui_tables.cpp.s
.PHONY : src/vendor/imgui/imgui_tables.cpp.s

src/vendor/imgui/imgui_widgets.o: src/vendor/imgui/imgui_widgets.cpp.o
.PHONY : src/vendor/imgui/imgui_widgets.o

# target to build an object file
src/vendor/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/vendor/imgui/imgui_widgets.cpp.o
.PHONY : src/vendor/imgui/imgui_widgets.cpp.o

src/vendor/imgui/imgui_widgets.i: src/vendor/imgui/imgui_widgets.cpp.i
.PHONY : src/vendor/imgui/imgui_widgets.i

# target to preprocess a source file
src/vendor/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/vendor/imgui/imgui_widgets.cpp.i
.PHONY : src/vendor/imgui/imgui_widgets.cpp.i

src/vendor/imgui/imgui_widgets.s: src/vendor/imgui/imgui_widgets.cpp.s
.PHONY : src/vendor/imgui/imgui_widgets.s

# target to generate assembly for a file
src/vendor/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/vendor/imgui/imgui_widgets.cpp.s
.PHONY : src/vendor/imgui/imgui_widgets.cpp.s

src/vendor/implot/implot.o: src/vendor/implot/implot.cpp.o
.PHONY : src/vendor/implot/implot.o

# target to build an object file
src/vendor/implot/implot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/vendor/implot/implot.cpp.o
.PHONY : src/vendor/implot/implot.cpp.o

src/vendor/implot/implot.i: src/vendor/implot/implot.cpp.i
.PHONY : src/vendor/implot/implot.i

# target to preprocess a source file
src/vendor/implot/implot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/vendor/implot/implot.cpp.i
.PHONY : src/vendor/implot/implot.cpp.i

src/vendor/implot/implot.s: src/vendor/implot/implot.cpp.s
.PHONY : src/vendor/implot/implot.s

# target to generate assembly for a file
src/vendor/implot/implot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/vendor/implot/implot.cpp.s
.PHONY : src/vendor/implot/implot.cpp.s

src/vendor/implot/implot_demo.o: src/vendor/implot/implot_demo.cpp.o
.PHONY : src/vendor/implot/implot_demo.o

# target to build an object file
src/vendor/implot/implot_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/vendor/implot/implot_demo.cpp.o
.PHONY : src/vendor/implot/implot_demo.cpp.o

src/vendor/implot/implot_demo.i: src/vendor/implot/implot_demo.cpp.i
.PHONY : src/vendor/implot/implot_demo.i

# target to preprocess a source file
src/vendor/implot/implot_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/vendor/implot/implot_demo.cpp.i
.PHONY : src/vendor/implot/implot_demo.cpp.i

src/vendor/implot/implot_demo.s: src/vendor/implot/implot_demo.cpp.s
.PHONY : src/vendor/implot/implot_demo.s

# target to generate assembly for a file
src/vendor/implot/implot_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/vendor/implot/implot_demo.cpp.s
.PHONY : src/vendor/implot/implot_demo.cpp.s

src/vendor/implot/implot_items.o: src/vendor/implot/implot_items.cpp.o
.PHONY : src/vendor/implot/implot_items.o

# target to build an object file
src/vendor/implot/implot_items.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/vendor/implot/implot_items.cpp.o
.PHONY : src/vendor/implot/implot_items.cpp.o

src/vendor/implot/implot_items.i: src/vendor/implot/implot_items.cpp.i
.PHONY : src/vendor/implot/implot_items.i

# target to preprocess a source file
src/vendor/implot/implot_items.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/vendor/implot/implot_items.cpp.i
.PHONY : src/vendor/implot/implot_items.cpp.i

src/vendor/implot/implot_items.s: src/vendor/implot/implot_items.cpp.s
.PHONY : src/vendor/implot/implot_items.s

# target to generate assembly for a file
src/vendor/implot/implot_items.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/vendor/implot/implot_items.cpp.s
.PHONY : src/vendor/implot/implot_items.cpp.s

src/vendor/stb/stb_image.o: src/vendor/stb/stb_image.cpp.o
.PHONY : src/vendor/stb/stb_image.o

# target to build an object file
src/vendor/stb/stb_image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/vendor/stb/stb_image.cpp.o
.PHONY : src/vendor/stb/stb_image.cpp.o

src/vendor/stb/stb_image.i: src/vendor/stb/stb_image.cpp.i
.PHONY : src/vendor/stb/stb_image.i

# target to preprocess a source file
src/vendor/stb/stb_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/vendor/stb/stb_image.cpp.i
.PHONY : src/vendor/stb/stb_image.cpp.i

src/vendor/stb/stb_image.s: src/vendor/stb/stb_image.cpp.s
.PHONY : src/vendor/stb/stb_image.s

# target to generate assembly for a file
src/vendor/stb/stb_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RTPlot.dir/build.make CMakeFiles/RTPlot.dir/src/vendor/stb/stb_image.cpp.s
.PHONY : src/vendor/stb/stb_image.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... RTPlot"
	@echo "... src/core/DeviceManager.o"
	@echo "... src/core/DeviceManager.i"
	@echo "... src/core/DeviceManager.s"
	@echo "... src/core/RTPlotCore.o"
	@echo "... src/core/RTPlotCore.i"
	@echo "... src/core/RTPlotCore.s"
	@echo "... src/core/RTPlotFunctions.o"
	@echo "... src/core/RTPlotFunctions.i"
	@echo "... src/core/RTPlotFunctions.s"
	@echo "... src/files/FileManager.o"
	@echo "... src/files/FileManager.i"
	@echo "... src/files/FileManager.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/plotting/ColorPalette.o"
	@echo "... src/plotting/ColorPalette.i"
	@echo "... src/plotting/ColorPalette.s"
	@echo "... src/plotting/Logger.o"
	@echo "... src/plotting/Logger.i"
	@echo "... src/plotting/Logger.s"
	@echo "... src/plotting/PlotData.o"
	@echo "... src/plotting/PlotData.i"
	@echo "... src/plotting/PlotData.s"
	@echo "... src/plotting/Plotter.o"
	@echo "... src/plotting/Plotter.i"
	@echo "... src/plotting/Plotter.s"
	@echo "... src/plotting/RealTimePlot.o"
	@echo "... src/plotting/RealTimePlot.i"
	@echo "... src/plotting/RealTimePlot.s"
	@echo "... src/plotting/RollingBuffer.o"
	@echo "... src/plotting/RollingBuffer.i"
	@echo "... src/plotting/RollingBuffer.s"
	@echo "... src/serial/SerialDevice.o"
	@echo "... src/serial/SerialDevice.i"
	@echo "... src/serial/SerialDevice.s"
	@echo "... src/serial/SerialPlotter.o"
	@echo "... src/serial/SerialPlotter.i"
	@echo "... src/serial/SerialPlotter.s"
	@echo "... src/serial/SerialPort.o"
	@echo "... src/serial/SerialPort.i"
	@echo "... src/serial/SerialPort.s"
	@echo "... src/vendor/imgui/imgui.o"
	@echo "... src/vendor/imgui/imgui.i"
	@echo "... src/vendor/imgui/imgui.s"
	@echo "... src/vendor/imgui/imgui_demo.o"
	@echo "... src/vendor/imgui/imgui_demo.i"
	@echo "... src/vendor/imgui/imgui_demo.s"
	@echo "... src/vendor/imgui/imgui_draw.o"
	@echo "... src/vendor/imgui/imgui_draw.i"
	@echo "... src/vendor/imgui/imgui_draw.s"
	@echo "... src/vendor/imgui/imgui_impl_glfw.o"
	@echo "... src/vendor/imgui/imgui_impl_glfw.i"
	@echo "... src/vendor/imgui/imgui_impl_glfw.s"
	@echo "... src/vendor/imgui/imgui_impl_opengl3.o"
	@echo "... src/vendor/imgui/imgui_impl_opengl3.i"
	@echo "... src/vendor/imgui/imgui_impl_opengl3.s"
	@echo "... src/vendor/imgui/imgui_tables.o"
	@echo "... src/vendor/imgui/imgui_tables.i"
	@echo "... src/vendor/imgui/imgui_tables.s"
	@echo "... src/vendor/imgui/imgui_widgets.o"
	@echo "... src/vendor/imgui/imgui_widgets.i"
	@echo "... src/vendor/imgui/imgui_widgets.s"
	@echo "... src/vendor/implot/implot.o"
	@echo "... src/vendor/implot/implot.i"
	@echo "... src/vendor/implot/implot.s"
	@echo "... src/vendor/implot/implot_demo.o"
	@echo "... src/vendor/implot/implot_demo.i"
	@echo "... src/vendor/implot/implot_demo.s"
	@echo "... src/vendor/implot/implot_items.o"
	@echo "... src/vendor/implot/implot_items.i"
	@echo "... src/vendor/implot/implot_items.s"
	@echo "... src/vendor/stb/stb_image.o"
	@echo "... src/vendor/stb/stb_image.i"
	@echo "... src/vendor/stb/stb_image.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

